package enums;

public enum WaitStrategy {
    CLICKABLE,
    PRESENCE,
    VISIBLE,
    NONE,
    INVISIBLE,
    SELECTED,
    ATTRIBUTE_CONTAINS,
    URL_CONTAINS,
    ALERT_PRESENT,
    ELEMENT_TO_BE_SELECTED,
    ELEMENT_TO_HAVE_TEXT

}
