name: run android test
on: push
jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.11'
      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium@2.5.3
          appium -v
          appium &>/dev/numm &
      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: arm64-v8a
          script: mvn clean test -Pandroid