name: Run Android Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest  # Switch to a Linux runner for better emulator compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: android-30
          ndk: '23.1.7779620'

      - name: Install Appium and dependencies (Linux)
        if: runner.os != 'macOS'
        run: |
          sudo apt-get update
          npm install -g appium
          appium --version

      - name: Install Appium and dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install carthage
          npm install -g appium
          appium --version

      - name: Install Android SDK Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64" "system-images;android-30;google_apis;x86"

      - name: List Available AVDs
        run: |
          avdmanager list avd
          avdmanager list device

      - name: Cleanup Previous Emulator
        run: |
          adb kill-server || true
          pkill -f 'emulator' || true

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Pixel_4  # Switch to Pixel_4
          disk-size: 2048M
          force-avd-creation: true  # Force AVD creation
          emulator-options: "-no-window -no-boot-anim"
          disable-animations: true
          emulator-boot-timeout: 600
          script: adb shell input keyevent 82

      - name: Debugging - Emulator State and Logs
        run: |
          adb devices
          adb shell getprop | grep ro.build.version
          adb logcat -d > emulator-log.txt
          ls -la $ANDROID_SDK_ROOT
          df -h  # Check disk space
          cat $ANDROID_SDK_ROOT/emulator/emulator64-crash.log || echo "No crash log found"

      - name: Upload Emulator Logs
        uses: actions/upload-artifact@v3
        with:
          name: Emulator Logs
          path: emulator-log.txt

      - name: Run Appium Tests
        run: |
          appium &
          mvn clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: target/surefire-reports/