name: Run Android Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'

      - name: Install Android SDK Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Pixel_5
          disk-size: 2048M
          force-avd-creation: true
          emulator-options: "-no-window -no-boot-anim"
          disable-animations: true
          emulator-boot-timeout: 600
          script: adb shell input keyevent 82

      - name: Debug AVD Configuration
        run: |
          avdmanager list avd
          emulator -list-avds
          adb devices

      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      - name: Retrieve Emulator Logs
        run: |
          cat $ANDROID_SDK_ROOT/emulator/emulator64-crash.log || echo "No crash log found"