name: run android test
on: push
jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.11'

      - name: pull the project into the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium@2.5.3
          appium -v
          appium &>/dev/null &

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64  # Changed to x86_64
          script: mvn clean test -Pandroid
